global:
  resolve_timeout: 5m
  smtp_from: ocp-acm-smtp@example.com.eg
  smtp_smarthost: 'mail.com.eg:25'
  smtp_hello: localhost
  smtp_require_tls: false
  smtp_auth_username: ocp-acm-smtp
  smtp_auth_password: test123
receivers:
  - name: Critical
    email_configs:
      - to: Openshift-Admins-Team@example.com.eg
        send_resolved: true
  - name: Default
  - name: core-team
    email_configs:
      - to: Core-Team-Support@example.com.eg
        send_resolved: true
  - name: integration-team
    email_configs:
      - to: Integration-Team-Support@example.com.eg
        send_resolved: true
  - name: devops-team
    email_configs:
      - to: devops-team-suuport@example.com.eg
        send_resolved: true
route:
  group_by: ['alertname', 'service']
  group_interval: 5m
  group_wait: 30s
  repeat_interval: 12h
  receiver: Default
  routes:
    - receiver: devops-team
      match_re:
        namespace: jenkins.*|sonarqube.*
        severity: critical
      continue: true
    - receiver: core-team
      match_re:
        namespace: core-.*
      continue: true
    - receiver: integration-team
      match_re:
        namespace: middleware-.*
      continue: true
